<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>Pokebot Dashboard</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css?<?php echo filemtime("css/bootstrap.css"); ?>" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/dashboard.css?<?php echo filemtime("css/dashboard.css"); ?>" rel="stylesheet">

    <link href="/css/bootstrap-editable.css?<?php echo filemtime("css/bootstrap-editable.css"); ?>" rel="stylesheet"/>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->

    <script src="/js/jquery.min.js"></script> 
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/docs.min.js"></script>
  </head>

  <body>  
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Pokebot Control Panel</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/">Dashboard</a></li>
            <li><a href="/settings">Settings</a></li>
            <!--<li><a href="/help">Help</a></li> -->
            <li>
              <?php
              echo("<a href=\"/");
              if (isset($_SESSION["session"])) {
                echo("logout");
              } else {
                echo("login");
              }
              echo("\">");
              if (isset($_SESSION["session"])) {
                echo("Logout");
              } else {
                echo("Login");
              }
              echo("</a>");
              ?></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row">
        <?php
        include($this->escape($this->page));
        ?>
      </div>
    </div>
  </body>
</html>