<h2 class="sub-header">PMC Support Email Validation</h2>

<div class="row">

    <?php
    foreach ($this->flashes() as $type => $messages) {
        foreach ($messages as $msg) {
            ?><h5 class = \"form-signin-heading\"><?php echo $msg; ?></h5><?php
        }
    }
    ?>

    <div class="col-md-5">
        <h3> Submit a new validation request</h3>
        <form action="add" method="POST">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>                        
                            <th style="width:50%"></th>
                            <th style="width:50%"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Email</td>
                            <td><input id="email" name="email" type="email"/></td>
                        </tr>
                        <tr>
                            <td>Ticket ID</td>
                            <td><input id="ticket" name="ticket" type="number"/></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td><input type="submit" id="sendRequest" class="btn button" value="Send Request" /></td>
                        </tr>
                    </tbody>
                </table>
            </div>  
        </form>
    </div>
    <div class="col-md-7">
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>                        
                        <th id="content_column" style="width:10%">Ticket</th>
                        <th id="name_column" style="width:50%">Email</th>
                        <th id="code_column" style="width:30%">Code</th>
                        <th id="action_column" style="width:10%">Clear</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->codes as $type => $set) { ?>
                        <tr>
                            <td><a href="http://www.planetminecraft.com/tickets/<?php echo $set['ticket']; ?>/"><?php echo $set['ticket']; ?></a></td>
                            <td><?php echo $set['email']; ?></td>
                            <td><?php echo $set['code']; ?></td>
                            <td>
                                <form action="clear" method="POST">
                                    <input id="validationId" name="ticket" value="<?php echo $set['id']; ?>" hidden/>
                                    <input type="submit" class="button btn btn-xs btn-danger" value="X"/>
                                </form>
                            </td>
                        </tr>
                    <?php } ?>                    
                </tbody>
            </table>
        </div>  
    </div>
</div>

<script type="text/javascript">
    $('#sendRequest').on('click', function (e) {
        if (!isEmail($('#email').val())) {
            e.preventDefault();
        } else if (!isNumber($('#ticket').val())) {
            e.preventDefault();
        }
    });

    function isEmail(email) {
        var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
        return email.length > 0 && regex.test(email);
    }

    function isNumber(number) {
        return number.length > 0 && !isNaN(number);
    }

</script>