<script src="/assets/js/hjt.js"></script>

<script type = "text/javascript">
    var viewModel = {
        tableLoaded: ko.observable(false),
        factoidTable: ko.observableArray(),
        gameTable: ko.observableArray(),
        loadData: loadData,
    };
    loadData();
</script>

<h2 class="sub-header">HJT Management</h2>
<div class="navbar navbar-default">
    <div class="container" style="margin-left: inherit;">
        <?php
        foreach ($this->flashes() as $type => $messages) {
            foreach ($messages as $msg) {
                ?><h5 class = \"form-signin-heading\"><?php echo $msg; ?></h5><?php
            }
        }
        ?>
        <div class="navbar-collapse collapse">
            <?php if ($this->perms['edit'] || $this->perms['delete']) { ?>
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Actions <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="/hjt/new">Create HJT</a></li>
                            <li><a href="#">Delete HJT</a></li>
                        </ul>
                    </li>
                </ul>
            <?php } ?>
        </div>
    </div>
</div>
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th id="name_column" style="width:20%">Name</th>
                <th id="content_column" style="width:80%">Content</th>
                <?php if ($this->perms['edit'] || $this->perms['delete']) { ?>
                    <th id="action_column" style="width:70px">Action</th>
                <?php } ?>
            </tr>
        </thead>
        <tbody data-bind="visible: tableLoaded, foreach: factoidTable" id="factoidtable">
            <tr>
                <td><p><strong data-bind="text: $data.name"></strong></p></td>
                <td><p data-bind="html: $data.content"></p></td>
                <?php if ($this->perms['edit'] || $this->perms['delete']) { ?>
                    <td>
                    <?php } ?>
                    <?php if ($this->perms['edit']) { ?>
                        <a style = "width:60px" class = "btn btn-xs btn-default" data-bind = "attr: {href: '/factoid/edit/' + $data.id}">Edit</a>
                    <?php } ?>
                    <?php if ($this->perms['delete']) { ?>
                        <a style = "width:60px" class = "btn btn-xs btn-default" data-bind = "attr: {href: '/factoid/delete/' + $data.id}">Delete</a>
                    <?php } ?>
                    <?php if ($this->perms['edit'] || $this->perms['delete']) { ?>
                    </td>
                <?php } ?>
                </td>
            </tr>
        </tbody>
    </table>
</div>

<script type="text/javascript">
    ko.applyBindings(viewModel);
</script>
