<h2 class="sub-header">HJT Management</h2>
<div class="navbar navbar-default">
    <div class="container" style="margin-left: inherit;">
        <?php
        foreach ($this->flashes() as $type => $messages) {
            foreach ($messages as $msg) {
                ?><h5 class = \"form-signin-heading\"><?php echo $msg; ?></h5><?php
            }
        }
        ?>
        <div class="navbar-header">
            <a class="navbar-brand">HJT Database</a>
        </div>
        <div class="navbar-collapse collapse">
            <?php if ((\AE97\Panel\Authentication::checkPermission('hjt.edit')) || (\AE97\Panel\Authentication::checkPermission('hjt.delete'))) { ?>
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Actions <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="/hjt/new">Create HJT</a></li>
                        </ul>
                    </li>
                </ul>
            <?php } ?>
        </div>
    </div>
</div>
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th id="name_column" style="width:20%">Matcher</th>
                <th id="content_column" style="width:80%">Content</th>
                <?php if ((\AE97\Panel\Authentication::checkPermission('hjt.edit')) || (\AE97\Panel\Authentication::checkPermission('hjt.delete'))) { ?>
                    <th id="action_column" style="width:70px">Action</th>
                <?php } ?>
            </tr>
        </thead>
        <tbody id="hjttable">
            <?php foreach ($this->hjts as $key => $val): ?>
            <tr>
                <td><?php echo $val['name']; ?></td>
                <td><?php echo $val['value']; ?></td>
                <?php if ((\AE97\Panel\Authentication::checkPermission('hjt.edit')) || (\AE97\Panel\Authentication::checkPermission('hjt.delete'))) { ?>
                    <td>
                    <?php } ?>
                    <?php if (\AE97\Panel\Authentication::checkPermission('hjt.edit')) { ?>
                        <a style="width:60px" class="btn btn-xs btn-default" href="edit/<?php echo $val['id']; ?>"}">Edit</a>
                    <?php } ?>
                    <?php if (\AE97\Panel\Authentication::checkPermission('hjt.delete')) { ?>
                        <a style="width:60px" class="btn btn-xs btn-default" href="delete/<?php echo $val['id']; ?>"}">Delete</a>
                    <?php } ?>
                    <?php if ((\AE97\Panel\Authentication::checkPermission('hjt.edit')) || (\AE97\Panel\Authentication::checkPermission('hjt.delete'))) { ?>
                    </td>
                <?php } ?>
            </tr>
             <?php endforeach; ?>
        </tbody>
    </table>
</div>
