<h2 class="sub-header">HJT Management</h2>
<style>
    th {
        font-weight: normal;
    }
</style>

<?php if (\AE97\Panel\Authentication::checkPermission('hjt.new')) { ?>
    <a class="btn btn-default" href="hjt/new">Add ban</a>
<?php } ?>

<div style="padding-bottom: 20px">
</div>

<table class="table table-striped table-responsive">
    <thead>
        <tr>
            <th style="width: 20%"><strong>Name</strong></th>
            <th style="width: 80%"><strong>Value</strong></th>
        </tr>
    </thead>
    <tbody id="factoidtable">
        <?php foreach ($this->hjt as $hjt): ?>
            <tr>
                <th><strong><?php echo $hjt['name']; ?></strong></th>
                <th><?php echo $hjt['value']; ?></th>
                <th>
                    <?php if (\AE97\Panel\Authentication::checkPermission('bans.delete')) { ?>
                        <a class="btn btn-default btn-sm" href="hjt/delete?name=<?php echo $hjt['name']; ?>">Delete</a>
                    <?php } ?>
                </th>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
