<div class="main">
    <h2 class="sub-header">HJT Management - Add new</h2>
</div>

<div class="container">
    <form style="width: 80%" name="edit" action="new" method="post" accept-charset="UTF-8">
        <div class="row" style="padding-bottom: 20px">
            <div class="col-md-3">
                <strong>Name:</strong>
            </div>
            <div class="col-md-6">
                <input name="name" required size="64" value=""/>
            </div>
        </div>
        <div class="row" style="padding-bottom: 20px">
            <div class="col-md-3">
                <strong>Value:</strong>
            </div>
            <div class="col-md-6">
                <input name="value" required size="64" value=""/>
            </div>
        </div>
    </form>
</div>
