<h2 class="sub-header">HJT Management</h2>

<div class="col-md-8">
    <table class="table table-responsive">
        <tbody>
        <?php
          foreach($this->hjts as $hjt) {
       echo '<tr>
              <th>Name</th>
              <th>'.$hjt['name'].'</th>
             </tr>
             <tr>
              <th>Value</th>
              <th>'.$hjt['value'].'</th>
             </tr>';
          }
        ?>
        </tbody>
    </table>
</div>
