<div class="col-sm-3 col-md-2 sidebar">
  <ul class="nav nav-sidebar">
    <li><a active=true href="/">Overview</a></li>
    <li><a href="/factoid">Factoid Database</a></li>
    <li><a href="/ban">Ban Management</a></li>
    <li><a href="/user">User Management</a></li>
    <li><a href="/bot">Bot Management</a></li>
  </ul>
</div>
<link href="css/signin.css?<?php echo filemtime("css/signin.css"); ?>" rel="stylesheet">
<div class="container">
  <form class = "form-signin" role = "form" action = "/resetpw" method = "post">
    <h3 class = "form-signin-heading">Request new password</h3>
    <?php
    foreach ($this->flashes() as $type => $messages):
      foreach ($messages as $msg):
        echo '<h5 class = \"form-signin-heading\">' . $msg . '</h5>';
      endforeach;
    endforeach;
    ?>
    <br>
    <input name = "email" type = "text" class = "form-control" placeholder = "Email" required autofocus>
    <br>
    <button class = "btn btn-lg btn-primary btn-block" type = "submit">Send reset link</button>
  </form>
</div>