<script type="text/javascript">
    var viewModel = {
        'unapprovedUsers': ko.observableArray(),
        'approve': <?php echo $this->perms['approveUser'] ?>,
        'delete': <?php echo $this->perms['deleteUser'] ?>

    };
    getList();

    function approveUser(value) {
        var posting = $.post('https://cp.ae97.net/admin/user/approve/' + value, {}, "json");
        posting.done(getList);
    }

    function deleteUser(value) {
        var posting = $.post('https://cp.ae97.net/admin/user/delete/' + value, {}, "json");
        posting.done(getList);
    }

    function getList() {
        $("#unapprovedTable").hide();
        var posting = $.post('https://cp.ae97.net/admin/user/list/unapproved', {}, "json");
        posting.done(function(data) {
            var json = JSON.parse(data);
            viewModel.unapprovedUsers.removeAll();
            for (var counter = 0; counter < json.length; counter++) {
                var item = json[counter];
                viewModel.unapprovedUsers.push({
                    'id': item.id,
                    'email': item.email,
                    'user': item.user
                });
            }
            $("#unapprovedTable").show();
        });
    }
</script>

<div class="col-lg-6">
    <h3 class="sub-header">Unapproved accounts</h3>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="unapprovedTable" data-bind="foreach: unapprovedUsers">
                <tr>
                    <td><p data-bind="text: $data.id"></p></td>
                    <td><p data-bind="text: $data.user"></p></td>
                    <td><p data-bind="text: $data.email"></p></td>
                    <td data-bind="visible: $parent.approve || $parent.delete">
                        <a data-bind="visible: $parent.approve, click: approveUser($data.id)" class="btn btn-xs btn-success">Approve</a>
                        <p data-bind="visible: $parent.delete"></p>
                        <a data-bind="visible: $parent.delete, click: deleteUser($data.id)" class="btn btn-xs btn-danger">Delete</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">  
  ko.applyBindings(viewModel);
</script>
