<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <div class="row">
        <h2 class="sub-header">Admin Panel</h2>
    </div>
    <div class="row">
        <ul>
            <li><a href="ban">Ban management</a></li>
            <li><a href="bot">Bot management</a></li>
            <li>User management</li>
            <ul>
                <li><a href="user/approve">Approve users</a></li>
                <li><a href="user/manage">Manage user groups</a></li>
            </ul>
        </ul>
    </div>
</div>