<div class="main">
    <div class="row">
        <h2 class="sub-header">Admin Panel</h2>
    </div>
    <div class="row">
        <ul>
            <li><a href="ban">Ban management</a></li>
            <li><a href="bot">Bot management</a></li>
            <li><a href="user">User management</a></li>
            <ul>
                <li><a href="user/approve">Approve users</a></li>
                <li><a href="user/manage">Manage user permissions</a></li>
            </ul>
        </ul>
    </div>
</div>