<div class="main">
    <div class="row">
        <h2 class="sub-header">Settings</h2>
    </div>
    <div class="row">
        <body>
            <div class="form-group">
                <form>
                    <h3>Change password</h3>
                    <p>Old password: <input type="text"></input></p>
                    <p>New password: <input type="password" name="newpw"></input></p>
                </form>
            </div>
        </body>
    </div>
</div>