<div class="col-sm-3 col-md-2 sidebar">
  <ul class="nav nav-sidebar">
    <li><a href="/">Overview</a></li>
    <li class="active"><a href="/factoid">Factoid Database</a></li>
    <li><a href="/ban">Ban Management</a></li>
    <li><a href="/user">User Management</a></li>
    <li><a href="/bot">Bot Management</a></li>
  </ul>
</div>

<script type="text/javascript">
  function loadData(game) {
    if (game === null) {
      game = "minecraft";
    }
    viewModel.tableLoaded(false);
    var posting = $.post('factoid/get', {db: game}, "json");
    posting.done(parseData);
  }

  function parseData(data) {
    var json = JSON.parse(data);
    viewModel.gameTable.removeAll();
    viewModel.factoidTable.removeAll();
    for (var counter = 0; counter < json.games.length; counter++) {
      var game = json.games[counter];
      viewModel.gameTable.push({'displayname': game.displayname, 'idname': game.idname});
    }

    for (var counter = 0; counter < json.factoids.length; counter++) {
      var item = json.factoids[counter];
      viewModel.factoidTable.push({
        'id': item.id,
        'name': item.name,
        'game': item.game,
        'content': item.content
      });
    }
    viewModel.tableLoaded(true);
    //viewModel.factoidTable.extend({rateLimit: 500});
  }

  function loadDataFromMenu(data, event) {
    loadData(data.idname);
  }
</script>

<script type="text/javascript">
  var viewModel = {
    tableLoaded: ko.observable(false),
    factoidTable: ko.observableArray(),
    gameTable: ko.observableArray(),
    editPerm: ko.observable(false),
    deletePerm: ko.observable(false),
    loadData: loadData
  };
  loadData("minecraft");
</script>

<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
  <h2 class="sub-header">Factoid Management</h2>
  <div class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand">Factoid Database - <a id="gamename" class="navbar-brand"><?php echo $this->game == null || !isset($this->gamelist[$this->game]) ? "All databases" : $this->gamelist[$this->game] ?></a></a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Select Database <b class="caret"></b></a>
            <ul  data-bind="foreach: gameTable" id="dbList" class="dropdown-menu">
              <li data-bind="click: loadDataFromMenu"><a data-bind="text: $data.displayname"></a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th id="id_column" style="width:50px">ID</th>
          <th id="name_column" style="width:200px">Name</th>
          <th id="content_column" style="width:500px">Content</th>
          <th id="action_column" data-bind="visible: editPerm, visible: deletePerm" style="width:50px">Action</th>
        </tr>
      </thead>
      <tbody data-bind="visible: tableLoaded, foreach: factoidTable" id="factoidtable">
        <tr>
          <td><p><em data-bind="text: $data.id"></em></p></td>
          <td><p><strong data-bind="text: $data.name"></strong></p></td>
          <td><p data-bind="text: $data.content"></p></td>
          <td data-bind="visible: $parent.editPerm, visible: $parent.deletePerm"></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<script type="text/javascript">
  ko.applyBindings(viewModel);
</script>