<div class="col-sm-3 col-md-2 sidebar">
  <ul class="nav nav-sidebar">
    <li><a href="/">Overview</a></li>
    <li class="active"><a href="/factoid">Factoid Database</a></li>
    <li><a href="/ban">Ban Management</a></li>
    <li><a href="/user">User Management</a></li>
    <li><a href="/bot">Bot Management</a></li>
  </ul>
</div>
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
  <h2 class="sub-header">Factoid Management</h2>
  <div class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand">Factoid Database - <?php echo $this->game == null || !isset($this->gamelist[$this->game]) ? "All databases" : $this->gamelist[$this->game] ?></a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Select Database <b class="caret"></b></a>
            <ul id="dbListings" class="dropdown-menu">
            </ul>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>

  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th style="width:50px">ID</th>
          <th style="width:200px">Name</th>
          <th style="width:200px"><?php
            if ($this->game == null) {
              echo 'Game';
            }
            ?></th>
          <th style="width:500px">Content</th>
          <th style="width:50px"><?php
            $display = false;
            foreach ($this->perms as $type => $perm):
              if ($perm) {
                $display = true;
              }
            endforeach;
            $display = true;
            if ($display) {
              echo 'Action';
            }
            ?></th>
        </tr>
      </thead>
      <tbody id="factoidtable">
      </tbody>
    </table>
  </div>
</div>

<script src="/js/bootstrap-editable.js"></script>

<script src="/js/factoid.js"></script>
<script type="text/javascript">
  var game = <?php echo $this->game == null || !isset($this->gamelist[$this->game]) ? "null" : $this->gamelist[$this->game] ?>;
  var perms = <?php echo json_encode($this->perms); ?>;
  FACTOID.load(game, perms);
</script>
