<link href="/assets/css/bootstrap-markdown.min.css?<?php echo filemtime("../assets/css/bootstrap-markdown.min.css"); ?>" rel="stylesheet">
<link href="/assets/fonts/glyphicons-halflings-regular.woff" rel="font">
<script src="/assets/js/bootstrap-markdown.js"></script>

<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <h2 class="sub-header">Factoid Management</h2>
    <div class="navbar navbar-default">
        <div class="container">
            <form style="width: 80%" name="edit" action="/factoid/submit-edit" method="post" accept-charset="UTF-8">
                <p><strong>ID:</strong> <em><?php echo $this->id; ?></em><input type="hidden" name= "id" value="<?php echo $this->id; ?>"></input></p>
                <p><strong>Name:</strong> <strong><?php echo $this->name; ?></strong><input type="hidden" name="name" value="<?php echo $this->name; ?>"></input></p>
                <p><strong>Content:</strong></p>
                <p>
                    <textarea id="content" name="content" data-provide="markdown"><?php echo $this->content; ?></textarea>
                </p>
                <p></p>
                <p></p>
                <button type="submit" style="width:75px" class="btn btn-xs btn-warning" type="button">Edit</button>
            </form>
            <p></p>
            <p></p>
            <a style="width:75px" class="btn btn-xs btn-danger" href="/factoid/<?php echo $this->game; ?>">Cancel</a>
            <p></p>
            <p></p>
            <p></p>
            <p></p>
            <p></p>
        </div>
    </div>
</div>

<script type="text/javascript">
    $("#content").markdown({
        fullscreen: {
            enable: false
        }
    });
    var markdown = $("#content").data("markdown");
    markdown.hideButtons(["cmdUrl", "cmdImage", "cmdList", "cmdList0", "cmdCode", "cmdQuote", "cmdPreview", "fullscreen"]);
</script>
