<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <h2 class="sub-header">Factoid Management</h2>
    <div class="navbar navbar-default">
        <div class="container">
            <form name="edit" action="/factoid/submit-edit" method="post" accept-charset="UTF-8">
                <p><strong>ID:</strong> <em><?php echo $this->id; ?></em><input type="hidden" name= "id" value="<?php echo $this->id; ?>"></input></p>
                <p><strong>Name:</strong> <strong><?php echo $this->name; ?></strong><input type="hidden" name="name" value="<?php echo $this->name; ?>"></input></p>
                <p><strong>Content:</strong></p>
                <p><textarea name="content" rows="6" cols="120"><?php echo $this->content; ?></textarea></p>
                <p></p>
                <p></p>
                <button type="submit" style="width:75px" class="btn btn-xs btn-warning" type="button">Edit</button>
            </form>
            <p></p>
            <p></p>
            <a style="width:75px" class="btn btn-xs btn-danger" href="/factoid/">Cancel</a>
            <p></p>
            <p></p>
            <p></p>
            <p></p>
            <p></p>
        </div>
    </div>
</div>