<link href="/assets/css/signin.min.css?<?php echo filemtime(__DIR__ . '/../../assets/css/signin.min.css'); ?>" rel="stylesheet">

<form class = "form-signin" role = "form" action = "/auth/login?redirect=<?php echo ($this->redirect !== null) ? $this->redirect : "/" ?>" method = "post">
    <h3 class = "form-signin-heading">Login</h3>
    <?php
    foreach ($this->flashes() as $type => $messages) {
        foreach ($messages as $msg) {
            ?><h5 class = \"form-signin-heading\"><?php echo $msg; ?></h5><?php
        }
    }
    ?>
    <input name = "email" type = "text" class = "form-control" placeholder = "Email" required autofocus>
    <input name = "password" type = "password" class = "form-control" placeholder = "Password" required>
    <button class = "btn btn-primary btn-block" type = "submit">Login</button>
    <p></p>
    <p><a href='/auth/resetpw'>Forgot password</a></p>
    <p><a href='/auth/register'>Register</a></p>
</form>