<link href="/assets/css/signin.min.css?<?php echo filemtime(__DIR__ . '/../../assets/css/signin.min.css'); ?>" rel="stylesheet">
<div class="container">
    <form class = "form-signin" role = "form" action = "/auth/resetpw" method = "post">
        <h3 class = "form-signin-heading">Request new password</h3>
        <?php
        foreach ($this->flashes() as $type => $messages) {
            foreach ($messages as $msg) {
                ?><h5 class = \"form-signin-heading\"><?php echo $msg; ?></h5><?php
            }
        }
        ?>
        <br>
        <input name = "email" type = "text" class = "form-control" placeholder = "Email" required autofocus>
        <br>
        <button class = "btn btn-lg btn-primary btn-block" type = "submit">Send reset link</button>
    </form>
</div>