<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Pokebot Control Panel</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <?php
                $isset = isset($_SESSION['session']);
                if ($isset) {
                    echo '<li><a href="/settings">Settings</a></li>';
                }
                ?>
                <li><a href="/auth/<?php echo $isset ? "logout" : "login"; ?><?php ?>"><?php echo $isset ? "Logout" : "Login"; ?></a></li>
            </ul>
        </div>
    </div>
</div>