<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="https://cp.ae97.net #Minecrafthelp Control Panel">
    <meta name="author" content="Lord_Ralex">
    <link rel="shortcut icon" href="/assets/ico/favicon.ico">

    <title>Pokebot Dashboard</title>

    <link href="/assets/css/bootstrap.min.css?<?php echo filemtime("../assets/css/bootstrap.css"); ?>" rel="stylesheet">
    <link href="/assets/css/dashboard.min.css?<?php echo filemtime("../assets/css/dashboard.css"); ?>" rel="stylesheet">

    <script src="/assets/js/jquery.min.js?<?php echo filemtime("../assets/js/jquery.min.js"); ?>"></script>
    <script src="/assets/js/bootstrap.min.js?<?php echo filemtime("../assets/js/bootstrap.min.js"); ?>"></script>
    <script src="/assets/js/docs.min.js?<?php echo filemtime("../assets/js/docs.min.js"); ?>"></script>
    <script src="/assets/js/knockout.min.js?<?php echo filemtime("../assets/js/knockout.min.js"); ?>"></script>
    <script src="/assets/js/core.js?<?php echo filemtime("../assets/js/core.js"); ?>"></script>
</head>