<div class="col-sm-3 col-md-2 sidebar">
    <ul class="nav nav-sidebar">
        <li><a href="/">Overview</a></li>
        <li><a href="/factoid">Factoid Database</a></li>
        <?php
        if (isset($_SESSION['session'])) {
            echo '<li><a href="/cp/admin/ban">Ban Management</a></li>
            <li><a href="/cp/admin/user">User Management</a></li>
            <li><a href="/cp/admin/bot">Bot Management</a></li>';
        }
        ?>
    </ul>
</div>