<div class="col-sm-3 col-md-2 sidebar">
  <ul class="nav nav-sidebar">
    <li><a href="/">Overview</a></li>
    <li class="active"><a href="/factoid">Factoid Database</a></li>
    <li><a href="/ban">Ban Management</a></li>
    <li><a href="/user">User Management</a></li>
    <li><a href="/bot">Bot Management</a></li>
  </ul>
</div>
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
  <h2 class="sub-header">Factoid Management</h2>          
  <div class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand">Factoid Database - <?php echo $this->game == null || !isset($this->gamelist[$this->game]) ? "All databases" : $this->gamelist[$this->game] ?></a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Select Database <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="/factoid">All</a></li>
              <?php
              foreach ($this->gamelist as $games => $game):
                echo '<li><a href="/factoid?db=' . $game['idname'] . '">' . $game['displayname'] . '</a></li>';
                echo "\r";
              endforeach;
              ?>
            </ul>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>

  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th style="width:50px">ID</th>
          <th style="width:200px">Name</th>
          <th style="width:200px"><?php
            if ($this->game == null) {
              echo 'Game';
            }
            ?></th>
          <th style="width:500px">Content</th>
          <th style="width:50px"><?php
            $display = false;
            foreach ($this->perms as $type => $perm):
              if ($perm) {
                $display = true;
              }
            endforeach;
            $display = true;
            if ($display) {
              echo 'Action';
            }
            ?></th>
        </tr>
      </thead>
      <tbody>
        <?php
        echo "\r\n";
        $perms = $this->perms;
        $total = count($this->factoids);
        echo "\r\n";
        foreach ($this->factoids as $type => $msg):
          echo '<tr>';
          echo '<td><italics>' . $msg['id'] . '</italics></td>  ';
          echo '<td><strong id="name_' . $msg['id'] . '" data-pk="' . $msg['id'] . '">' . $msg['name'] . '</strong></td> ';
          echo '<td>';
          if ($this->game == null) {
            echo '<p id="game_' . $msg['id'] . '" data-pk="' . $msg['id'] . '">' . $msg['game'] . '</p>';
          }
          echo '</td>';
          echo '<td><p id="content_' . $msg['id'] . '" data-pk="' . $msg['id'] . '">' . make_urls_into_links(str_replace(';;', " <br><br> ", $msg['content'])) . '</p></td> ';
          echo '<td>';
          #if ($perms['edit']) {
          echo '<button id="editbutton_' . $msg['id'] . '" data-factoid="' . $msg['id'] . '" type="button" class="btn btn-xs btn-warning editbutton">Edit</button>';
          echo '<br>';
          #}
          if ($perms['delete']) {
            echo '<button id="deletebutton" data-factoid="' . $msg['id'] . '" type="button" class="btn btn-xs btn-danger">Delete</button>';
          }
          echo '</td> ';
          echo "</tr>\r\n";
        endforeach;

        function make_urls_into_links($plain_text) {
          return preg_replace('@(https?://([-\w\.]+[-\w])+(:\d+)?(/([\w/_\.#-~]*(\?\S+)?)?)?)@', '<a href="$1">$1</a>', $plain_text);
        }
        ?>
      </tbody>
    </table>
  </div>
</div>
<script src="js/bootstrap-editable.js"></script>

<script type="text/javascript">

  $.fn.editable.defaults.mode = 'inline';
  $('.editable-input').parents('form').removeClass('form-inline');

  function toggleEditable(name, inputId, type)
  {
    //throw new Error('#' + name + "_" + inputId);
    var input = $('#' + name + "_" + inputId);
    input.editable({
      highlight: false,
      toggle: 'manual',
      onblur: 'ignore',
      rows: 4,
      type: type,
      showbuttons: false
    });
    input.editable('toggle');
  }

  $('.editbutton').click(function(e) {
    e.stopPropagation();
    toggleEditable("name", $(this).attr('data-factoid'), "text");
    toggleEditable("game", $(this).attr('data-factoid'), "text");
    toggleEditable("content", $(this).attr('data-factoid'), "textarea");
  });

  $('.savebutton').click(function(e) {
    e.stopPropagation();
    toggleEditable("name", $(this).attr('data-factoid'), "text");
    toggleEditable("game", $(this).attr('data-factoid'), "text");
    toggleEditable("content", $(this).attr('data-factoid'), "textarea");
  });

</script>
