<div class="col-sm-3 col-md-2 sidebar">
  <ul class="nav nav-sidebar">
    <li><a href="/">Overview</a></li>
    <li class="active"><a href="/factoid">Factoid Database</a></li>
    <li><a href="/ban">Ban Management</a></li>
    <li><a href="/user">User Management</a></li>
    <li><a href="/bot">Bot Management</a></li>
  </ul>
</div>
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
  <h2 class="sub-header">Factoid Management</h2>
  <div class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand">Factoid Database - <?php echo $this->game == null || !isset($this->gamelist[$this->game]) ? "All databases" : $this->gamelist[$this->game] ?></a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Select Database <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="/factoid">All</a></li>
              <?php
              foreach ($this->gamelist as $games => $game):
                echo '<li><a href="/factoid?db=' . $game['idname'] . '">' . $game['displayname'] . '</a></li>';
                echo "\r";
              endforeach;
              ?>
            </ul>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>

  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th style="width:50px">ID</th>
          <th style="width:200px">Name</th>
          <th style="width:200px"><?php
            if ($this->game == null) {
              echo 'Game';
            }
            ?></th>
          <th style="width:500px">Content</th>
          <th style="width:50px"><?php
            $display = false;
            foreach ($this->perms as $type => $perm):
              if ($perm) {
                $display = true;
              }
            endforeach;
            $display = true;
            if ($display) {
              echo 'Action';
            }
            ?></th>
        </tr>
      </thead>
      <tbody>
        <?php
        $perms = $this->perms;
        $total = count($this->factoids);
        foreach ($this->factoids as $type => $msg):
          ?>
          <tr>
            <td><em><?php echo($msg['id']) ?></em></td>
            <td><strong id="name_<?php echo $msg['id']; ?>" data-pk="<?php echo $msg['id']; ?>"><?php echo $msg['name']; ?></strong></td>
            <td><?php
              if ($this->game == null) {
                echo '<p id="game_' . $msg['id'] . '" data-pk="' . $msg['id'] . '">' . $msg['game'] . '</p>';
              }
              ?></td>
            <td><p id="content_<?php echo $msg['id']; ?>" data-pk="<?php echo $msg['id']; ?>"><?php echo make_urls_into_links(str_replace(';;', " <br><br> ", $msg['content'])); ?></p></td>
            <td><?php
              if ($perms['edit']) {
                echo '<button id="editbutton_' . $msg['id'] . '" data-factoid="' . $msg['id'] . '" type="button" class="btn btn-xs btn-warning editbutton">Edit</button>';
                echo '<button id="savebutton_' . $msg['id'] . '" data-factoid="' . $msg['id'] . '" type="button" class="btn btn-xs btn-success savebutton">Save</button>';
                echo '<script>$("#savebutton_' . $msg['id'] . '").hide()</script>';
              }
              ?>
              <?php
              if ($perms['delete']) {
                echo '<button id="deletebutton" data-factoid="' . $msg['id'] . '" type="button" class="btn btn-xs btn-danger">Delete</button>';
              }
              ?></td>
          </tr>
        <?php endforeach; ?>

        <?php

        function make_urls_into_links($plain_text) {
          return preg_replace('@(https?://([-\w\.]+[-\w])+(:\d+)?(/([\w/_\.#-~]*(\?\S+)?)?)?)@', '<a href="$1">$1</a>', $plain_text);
        }
        ?>
      </tbody>
    </table>
  </div>
</div>

<script src="js/bootstrap-editable.js"></script>

<script type="text/javascript">

  $.fn.editable.defaults.mode = 'inline';
  $('.editable-input').parents('form').removeClass('form-inline');

  function toggleEditable(name, inputId, type)
  {
    //throw new Error('#' + name + "_" + inputId);
    var input = $('#' + name + "_" + inputId);

    if (!input.hasClass("editable")) {
      input.editable({
        highlight: false,
        toggle: 'manual',
        onblur: 'ignore',
        rows: 4,
        type: type,
        showbuttons: false,
        innerClass: 'editable-input-textarea'
      });
      input.editable('enable');
      input.editable('toggle');
    } else {
      input.editable('toggle');
      input.editable('disable');
      input.editable('destroy');
      input.css({display: 'block'});
    }
  }

  $('.editbutton').click(function(e) {
    e.stopPropagation();
    toggleEditable("name", $(this).attr('data-factoid'), "text");
    toggleEditable("game", $(this).attr('data-factoid'), "text");
    toggleEditable("content", $(this).attr('data-factoid'), "textarea");
    $(this).hide();
    $('#savebutton_' + $(this).attr('data-factoid')).show();
  });

  $('.savebutton').click(function(e) {
    e.stopPropagation();
    toggleEditable("name", $(this).attr('data-factoid'), "text");
    toggleEditable("game", $(this).attr('data-factoid'), "text");
    toggleEditable("content", $(this).attr('data-factoid'), "textarea");
    $(this).hide();
    $('#editbutton_' + $(this).attr('data-factoid')).show();
  });

</script>
