<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="https://cp.ae97.net #Minecrafthelp Control Panel">
  <meta name="author" content="Lord_Ralex">
  <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

  <title>Pokebot Dashboard</title>

  <!-- Bootstrap core CSS -->
  <link href="/css/bootstrap.css?<?php echo filemtime("css/bootstrap.css"); ?>" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="/css/dashboard.css?<?php echo filemtime("css/dashboard.css"); ?>" rel="stylesheet">

  <script src="/js/jquery.min.js"></script> 
  <script src="/js/bootstrap.min.js"></script>
  <script src="/js/docs.min.js"></script>
  <script src="/js/knockout.js"></script>
</head>