<div class="main">
    <h2 class="sub-header">Ban Management</h2>
</div>

<?php
$flashes = $this->flashes();
if (count($flashes) > 0) {
    ?><div class="row">
        <div class="col-md-4 col-md-offset-1 alert alert-danger form-signin-heading"><?php
            foreach ($flashes as $type => $messages) {
                foreach ($messages as $msg) {
                    ?>
                    <h5><?php echo $msg; ?></h5>
                    <?php
                }
            }
            ?></div>
    </div>
    <?php
}
?>

<style>
    th {
        font-weight: normal;
    }
</style>

<?php if (\AE97\Panel\Authentication::checkPermission('bans.new')) { ?>
    <a class="btn btn-default" href="ban/new">Add ban</a>
<?php } ?>

<div style="padding-bottom: 20px">
</div>

<table class="table table-striped table-responsive">
    <thead>
        <tr>
            <th style="width: 5%"><strong>Id</strong></th>
            <th style="width: 15%"><strong>Mask</strong></th>
            <th><strong>Create date (UTC)</strong></th>
            <th><strong>Unban date (UTC)</strong></th>
            <th><strong>Created by</strong></th>
            <th><strong>Channels</strong></th>
            <th><strong>Reason</strong></th>
            <th style="width: 5%"><strong>Action</strong></th>
        </tr>
    </thead>
    <tbody id="factoidtable">
        <?php foreach ($this->bans as $key => $val): ?>
            <tr>
                <th><strong><?php echo $val['id']; ?></strong></th>
                <th><?php echo $val['content']; ?></th>
                <th><?php echo $val['issueDate']; ?></th>
                <th><?php echo $val['expireDate'] ? : "Permanent"; ?></th>
                <th><?php echo $val['issuer']; ?></th>
                <th><?php echo implode(", ", $val['channels']); ?></th>
                <th><?php echo $val['notes']; ?></th>
                <?php if (\AE97\Panel\Authentication::checkPermission('bans.expire')) { ?>
                    <th><a class="btn btn-default btn-sm" href="ban/expire?id=<?php echo $val['id']; ?>">Expire</a></th>
                    <?php } ?>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>