<h2 class="sub-header">Ban Management</h2>

<?php
$flashes = $this->flashes();
if (count($flashes) > 0) {
    ?><div class="row">
        <div class="col-md-4 col-md-offset-1 alert alert-danger form-signin-heading"><?php
            foreach ($flashes as $type => $messages) {
                foreach ($messages as $msg) {
                    ?>
                    <h5><?php echo $msg; ?></h5>
                    <?php
                }
            }
            ?></div>
    </div>
    <?php
}
?>

<style>
    th {
        font-weight: normal;
    }
</style>

<?php if (\AE97\Panel\Authentication::checkPermission('bans.new')) { ?>
    <a class="btn btn-default" href="ban/new">Add ban</a>
<?php } ?>

<div style="padding-bottom: 20px">
</div>

<table class="table table-striped table-responsive">
    <thead>
        <tr>
            <th style="width: 4%"><strong>Id</strong></th>
            <th style="width: 30%"><strong>Mask</strong></th>
            <th style="width: 10%"><strong>Expires</strong></th>
            <th style="width: 11%"><strong>Created by</strong></th>
            <th style="width: 12%"><strong>Channels</strong></th>
            <th style="width: 30%"><strong>Reason</strong></th>
            <th style="width: 8%"><strong>Action</strong></th>
        </tr>
    </thead>
    <tbody id="factoidtable">
        <?php foreach ($this->bans as $key => $val): ?>
            <tr>
                <th><strong><?php echo $val['id']; ?></strong></th>
                <th><?php echo $val['content']; ?></th>
                <th><span class="datedisplay" raw="<?php echo $val['expireDate'] ? : "Permanent"; ?>"></span></th>
                <th><?php echo $val['issuer']; ?></th>
                <th><?php echo implode(", ", $val['channels']); ?></th>
                <th><?php echo $val['notes']; ?></th>
                <th>
                    <a class="btn btn-default btn-sm" href="ban/view?id=<?php echo $val['id']; ?>">View</a>
                    <?php if (\AE97\Panel\Authentication::checkPermission('bans.expire')) { ?>
                        <a class="btn btn-default btn-sm" href="ban/expire?id=<?php echo $val['id']; ?>">Expire</a>
                    <?php } ?>
                </th>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<script type="text/javascript">
    $("span.datedisplay").each(function (index) {
        var item = $(this);
        var date = item.attr("raw");
        var dateString = date.split(" ")[0];
        var timeString = date.split(" ")[1];
        console.log(date);
        var dateObj = new Date(Date.UTC(
                dateString.split("-")[0],
                dateString.split("-")[1],
                dateString.split("-")[2],
                timeString.split(":")[0],
                timeString.split(":")[1],
                timeString.split(":")[2]
                ));
        item.text((dateObj.getMonth() + 1) + "/" + (dateObj.getDate()) + "/" + dateObj.getFullYear());
        item.attr('title', dateObj.toLocaleString());
    });
</script>