<div class="main">
    <h2 class="sub-header">Ban Management - Add ban</h2>
</div>

<div class="container">
    <?php
    $flashes = $this->flashes();
    if (count($flashes) > 0) {
        ?><div class="row">
            <div class="col-md-6 col-md-offset-1 alert alert-danger form-signin-heading"><?php
                foreach ($flashes as $type => $messages) {
                    foreach ($messages as $msg) {
                        ?>
                        <h5><?php echo $msg; ?></h5>
                        <?php
                    }
                }
                ?></div>
        </div>
        <?php
    }
    ?>
    <form style="width: 80%" name="edit" action="new" method="post" accept-charset="UTF-8">
        <div class="row" style="padding-bottom: 20px">
            <div class="col-md-3">
                <strong>Ban mask:</strong>
            </div>
            <div class="col-md-6">
                <input name="mask" required size="64" value="*!*@"/>
            </div>
        </div>
        <div class="row" style="padding-bottom: 20px">
            <div class="col-md-3">
                <strong>Kick message:</strong>
            </div>
            <div class="col-md-6">
                <input name="kickmessage" required size="64" value="You are banned from this channel"/>
            </div>
        </div>
        <div class="row" style="padding-bottom: 20px">
            <div class="col-md-3">
                <strong>Notes:</strong>
            </div>
            <div class="col-md-6">
                <textarea name="notes" cols="66" rows="4"></textarea>
            </div>
        </div>
        <div class="row" style="padding-bottom: 20px">
            <div class="col-md-3">
                <strong>Days to ban</strong> (0=perm)<strong>:</strong>
            </div>
            <div class="col-md-6">
                <input type="number" value="7" name="daysbanned" size="3" style="width: 75px" required/>
            </div>
        </div>
        <div class="row" style="padding-bottom: 20px">
            <div class="col-md-3">
                <strong>Channels </strong> ('all' for global)<strong>:</strong>
            </div>
            <div class="col-md-6">
                <input name="channels" required size="64" />
            </div>
        </div>

        <div class="row" style="padding-top: 20px">
            <button type="submit" class="btn btn-default">Add</button>
        </div>
        <?php if ($this->ban != null) { ?>
            <div class="row" style="padding-top: 20px">
                <a href="delete?id=<?php echo $this->ban['id']; ?>" class="btn btn-default">Delete</a>
            </div>
        <?php } ?>
    </form>
</div>