<h2 class="sub-header">Ban Management</h2>

<?php
$flashes = $this->flashes();
if (count($flashes) > 0) {
    ?><div class="row">
        <div class="col-md-4 col-md-offset-1 alert alert-danger form-signin-heading"><?php
            foreach ($flashes as $type => $messages) {
                foreach ($messages as $msg) {
                    ?>
                    <h5><?php echo $msg; ?></h5>
                    <?php
                }
            }
            ?></div>
    </div>
    <?php
}
?>

<div class="col-md-8">
    <table class="table table-responsive">
        <tbody>
            <tr>
                <th>Id</th>
                <th><?php echo $this->ban['id']; ?></th>
            </tr>
            <tr>
                <th>Applied by</th>
                <th><?php echo $this->ban['issuer']; ?></th>
            </tr>
            <tr>
                <th>Mask</th>
                <th><?php echo $this->ban['content']; ?></th>
            </tr>
            <tr>
                <th>Issue date</th>
                <th class="datedisplay" raw="<?php echo $this->ban['issueDate']; ?>"></th>
            </tr>
            <tr>
                <th>Expire date</th>
                <th class="datedisplay" raw="<?php echo $this->ban['expireDate']; ?>"></th>
            </tr>
            <tr>
                <th>Kick message</th>
                <th><?php echo $this->ban['kickmessage']; ?></th>
            </tr>
            <tr>
                <th>Channels</th>
                <th>
                    <?php foreach ($this->ban['channels'] as $channel) { ?>
                        <?php echo $channel; ?>
                        <br>
                    <?php } ?>
                </th>

            </tr>
            <tr>
                <th>Notes</th>
                <th><?php echo $this->ban['notes']; ?></th>
            </tr>
        </tbody>
    </table>
</div>


<script type="text/javascript">
    $("th.datedisplay").each(function (index) {
        var item = $(this);
        var date = item.attr("raw");
        var dateString = date.split(" ")[0];
        var timeString = date.split(" ")[1];
        var dateObj = new Date(Date.UTC(
                dateString.split("-")[0],
                dateString.split("-")[1],
                dateString.split("-")[2],
                timeString.split(":")[0],
                timeString.split(":")[1],
                timeString.split(":")[2]
                ));
        item.text(dateObj.toLocaleString());
    });
</script>