<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <script type="text/javascript" src="/assets/js/approval.js"></script>
    <script type="text/javascript">
        var viewModel = {
            'unapprovedUsers': ko.observableArray()
        };
    </script>

    <div class="col-lg-6">
        <h3 class="sub-header">Non-approved accounts</h3>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Username</th>
                        <th>Email</th>
                        <?php if ($this->perms['approveUser']) { ?>
                            <th>Action</th>
                        <?php } ?>
                    </tr>
                </thead>
                <tbody id="unapprovedTable" data-bind="foreach: unapprovedUsers">
                    <tr>
                        <td><p data-bind="text: $data.id"></p></td>
                        <td><p data-bind="text: $data.user"></p></td>
                        <td><p data-bind="text: $data.email"></p></td>
                        <?php if ($this->perms['approveUser']) { ?>
                            <td>
                                <a data-bind="click: approveUser.bind($data.id)" class="btn btn-xs btn-success">Approve</a>
                            </td>
                        <?php } ?>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    ko.applyBindings(viewModel);
    getUnapprovedUserList();
</script>