<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <script type="text/javascript" src="/assets/js/approval.js"></script>
    <script type="text/javascript">
        var viewModel = {
            'userList': ko.observableArray()
        };
    </script>

    <div class="col-lg-6">
        <h3 class="sub-header">User management</h3>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Username</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>