<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <script type="text/javascript" src="/assets/js/permissions.js"></script>
    <script type="text/javascript">
        var viewModel = {
            'users': ko.observableArray(),
            'edit': <?php echo $this->perms['editPerms'] ?>,
        };
    </script>
</div>

<script type="text/javascript">
    ko.applyBindings(viewModel);
</script>