<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <script type="text/javascript">
        var viewModel = {
            'users': ko.observableArray()
        };
<?php
foreach ($this->users as $user) {
    echo 'viewModel.users.push({name:"' . $user['name'] . '", id:"' . $user['id'] . '",uid:"' . $user['id'] . '"});';
}
?>
    </script>
    <div class='row'>
        <div class='col-md-2'>
            <h3>User Management</h3>
        </div>
        <div class='col-md-2'>
        </div>
    </div>

    <div class="row">
        <div class="col-md-1">Id</div>
        <div class="col-md-3">Username</div>
    </div>

    <div class="row" data-bind='foreach: users'>
        <div class="col-md-1">
            <span data-bind='text: id'></span>
        </div>
        <div class="col-md-3">
            <span data-bind='text: name'></span>
        </div>
        <div class="col-md-2">
            <a data-bind='attr: {href: "editpermissions/" + uid}'>Edit perms</a>
        </div>
    </div>
</div>

<script type="text/javascript">
    ko.applyBindings(viewModel);
</script>
