<div class="main">
    <h2 class="sub-header">Bot Management</h2>
    <div class="row">
        <div class="col-md-8">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>                        
                            <th style="width:40%">ID</th>
                            <th style="width:60%">Value</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->config as $type => $set) { ?>
                            <tr>
                        <form action="bot/edit" method="POST">
                            <td><?php echo $set['id']; ?></td>
                            <td>
                                <input id="id" name="id" value="<?php echo $set['id']; ?>" hidden />
                                <input class="form-control" id="value" name="value" value="<?php echo $set['val']; ?>"/>
                            </td>
                            <td>
                                <input type="submit" class="button btn btn-xs" value="Save"/>                                    
                            </td>
                        </form>
                        </tr>
                    <?php } ?>                    
                    </tbody>
                </table>
            </div>  
        </div>
    </div>
</div>