<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
  <h2 class="sub-header">User Management</h2>          
  <?php
  if ($this->perms['approveUser']) {
    include("approve-table.phtml");
  }
  if ($this->perms['editPerms']) {
    include('perms-table.phtml');
  }
  ?>
</div>

<script>
  function approveUser(value) {
    var form = document.createElement('form');
    form.setAttribute('method', 'post');
    form.setAttribute('action', 'https://cp.ae97.net/admin/user/approve/' + value);
    form.style.display = 'hidden';
    document.body.appendChild(form);
    form.submit();
  }

  function deleteUser(value) {
    var form = document.createElement('form');
    form.setAttribute('method', 'post');
    form.setAttribute('action', 'https://cp.ae97.net/admin/user/delete/' + value);
    form.style.display = 'hidden';
    document.body.appendChild(form);
    form.submit();
  }
</script>