<?php $isset = isset($_SESSION['session']); ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
        <meta name="viewport" content="width=device-width initial-scale=1.0">
        <meta name="description" content="https://cp.ae97.net #Minecrafthelp Control Panel">
        <meta name="author" content="Lord_Ralex">
        <link rel="shortcut icon" href="/assets/ico/favicon.ico">

        <title>Pokebot Dashboard</title>

        <link href="/assets/css/bootstrap.min.css?<?php echo filemtime("../assets/css/bootstrap.min.css"); ?>" rel="stylesheet">
        <link href="/assets/css/dashboard.min.css?<?php echo filemtime("../assets/css/dashboard.min.css"); ?>" rel="stylesheet">
        <!--<link href="/assets/css/custom.min.css?<?php echo filemtime("../assets/css/custom.min.css"); ?>" rel="stylesheet">-->

        <script src="/assets/js/jquery.min.js?<?php echo filemtime("../assets/js/jquery.min.js"); ?>"></script>
        <script src="/assets/js/bootstrap.min.js?<?php echo filemtime("../assets/js/bootstrap.min.js"); ?>"></script>
        <script src="/assets/js/docs.min.js?<?php echo filemtime("../assets/js/docs.min.js"); ?>"></script>
        <script src="/assets/js/knockout.min.js?<?php echo filemtime("../assets/js/knockout.min.js"); ?>"></script>
        <script src="/assets/js/Autolinker.min.js?<?php echo filemtime("../assets/js/Autolinker.min.js"); ?>"></script>
        <script src="/assets/js/core.js?<?php echo filemtime("../assets/js/core.js"); ?>"></script>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/">Pokebot Control Panel</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">                        
                        <?php if ($isset) { ?>
                            <li><a href="/settings">Settings</a></li>
                            <li><a href="/auth/logout">Logout</a></li>
                        <?php } else { ?>
                            <li><a href="/auth/login">Login</a></li>
                        <?php } ?>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li><a href="/">Overview</a></li>
                <li><a href="/factoid">Factoid Database</a></li>
                <?php if ($isset) { ?>
                    <li><a href="/admin/ban">Ban Management</a></li>
                    <li><a href="/admin/user">User Management</a></li>
                    <!--<li><a href="/admin/bot">Bot Management</a></li>-->
                    <li><a href="/pmc/email">PMC Ticket Emails</a></li>
                <?php } ?>
            </ul>
        </div>
        <div class="container-fluid">
            <div class="col-md-10 col-md-offset-2">
                <?php
                $page = $this->escape($this->page);
                if ($page != null) {
                    include($page);
                }
                ?>
            </div>
        </div>
    </body>
</html>